### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by freshlogic** [dylang/captionbot#2]
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at got.then.then.response (/Users/shawnmiller/GitHub/mehdown/node_modules/captionbot/index.js:36:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Looks like captionbot is returning an empty response. Any ideas?

**Comment by 110Percent** [comment]
Can confirm; getting 
`(node:9594) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected end of JSON input`
in my console. Doesn't look like CB is liking the input.

**Comment by rajkumar-osm** [comment]
Same problem here.
Did you guys find the solution

**Comment by dylang** [comment]
It looks like they are returning an empty string instead of a JSON object. Maybe Microsoft has changed the API in some way? 

I'm happy to accept a pull request that fixes the problem.

**Comment by toothlesspanda** [comment]
Yeah, same problem here... I would like to use this for my thesis. Any solution?

**Comment by Delivator** [comment]
I've crated a pull request (#3), should work with that.

**Comment by Delivator** [comment]
I would really appreciate it, if you could merge the pull request, because i want to use this in my project :D

**Comment by felipemullen** [comment]
@dylang pr(#3) doesn't seem to have any issues (although I don't personally like the hardcoded array access)
